# Generated by Django 6.0.7 on 2026-07-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact'), ('percentage', 'Percentage'), ('share', 'Share'), ('unequal', 'Unequal')], max_length=20),
        ),
    ]
